// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reserva_de_equipos.Models;

#nullable disable

namespace Reserva_de_equipos.Migrations
{
    [DbContext(typeof(DbReservaContext))]
    [Migration("20251027163611_Responsable_Rol")]
    partial class Responsable_Rol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reserva_de_equipos.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AreaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Area", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.AreaDisponible", b =>
                {
                    b.Property<int>("AreaDisponibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Area_DisponibleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaDisponibleId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.HasKey("AreaDisponibleId");

                    b.HasIndex("AreaId");

                    b.HasIndex("EquipoId");

                    b.ToTable("Area_Disponible", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Conductor", b =>
                {
                    b.Property<int>("ConductorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConductorId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ConductorId");

                    b.ToTable("Conductor", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Descripción")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresa", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<string>("ImagenJson")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_EquipoId");

                    b.HasKey("EquipoId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("TipoEquipoId");

                    b.ToTable("Equipo", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int?>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Inicio");

                    b.Property<bool>("Indefinido")
                        .HasColumnType("bit")
                        .HasColumnName("Indefinido");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Ubicación")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Responsable", b =>
                {
                    b.Property<int>("ResponsableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponsableId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ResponsableId");

                    b.HasIndex("RolId");

                    b.ToTable("Responsable", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripción")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Rol", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.TipoEquipo", b =>
                {
                    b.Property<int>("TipoEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_EquipoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEquipoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("IconoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("TipoEquipoId");

                    b.ToTable("Tipo_Equipo", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("AreaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", "Reserva");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Area", b =>
                {
                    b.HasOne("Reserva_de_equipos.Models.Empresa", "Empresa")
                        .WithMany("Areas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Area_Empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.AreaDisponible", b =>
                {
                    b.HasOne("Reserva_de_equipos.Models.Area", "Area")
                        .WithMany("AreaDisponibles")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK_Area_Disponible_Area");

                    b.HasOne("Reserva_de_equipos.Models.Equipo", "Equipo")
                        .WithMany("AreaDisponibles")
                        .HasForeignKey("EquipoId")
                        .IsRequired()
                        .HasConstraintName("FK_Area_Disponible_Equipo");

                    b.Navigation("Area");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Equipo", b =>
                {
                    b.HasOne("Reserva_de_equipos.Models.Responsable", "Responsable")
                        .WithMany("Equipos")
                        .HasForeignKey("ResponsableId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipo_Responsable");

                    b.HasOne("Reserva_de_equipos.Models.TipoEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .IsRequired()
                        .HasConstraintName("FK_Equipo_Tipo_Equipo");

                    b.Navigation("Responsable");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Reserva", b =>
                {
                    b.HasOne("Reserva_de_equipos.Models.Conductor", "Conductor")
                        .WithMany("Reservas")
                        .HasForeignKey("ConductorId");

                    b.HasOne("Reserva_de_equipos.Models.Equipo", "Equipo")
                        .WithMany("Reservas")
                        .HasForeignKey("EquipoId")
                        .HasConstraintName("FK_Reserva_Equipo");

                    b.HasOne("Reserva_de_equipos.Models.Usuario", "usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Conductor");

                    b.Navigation("Equipo");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Responsable", b =>
                {
                    b.HasOne("Reserva_de_equipos.Models.Rol", "Rol")
                        .WithMany("Responsables")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Usuario", b =>
                {
                    b.HasOne("Reserva_de_equipos.Models.Area", "Area")
                        .WithMany("Usuarios")
                        .HasForeignKey("AreaId")
                        .HasConstraintName("FK_Usuario_Area");

                    b.HasOne("Reserva_de_equipos.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Rol");

                    b.Navigation("Area");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Area", b =>
                {
                    b.Navigation("AreaDisponibles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Conductor", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Empresa", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Equipo", b =>
                {
                    b.Navigation("AreaDisponibles");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Responsable", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Rol", b =>
                {
                    b.Navigation("Responsables");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Reserva_de_equipos.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
